# Generated by Django 2.1.7 on 2019-05-25 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20190512_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=False)),
                ('date_create_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_convidados', to=settings.AUTH_USER_MODEL)),
                ('racha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Racha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='racha',
            name='membros_ingressado',
            field=models.ManyToManyField(through='core.Membros', to=settings.AUTH_USER_MODEL),
        ),
    ]
