# Generated by Django 2.1.7 on 2019-05-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190525_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racha',
            old_name='membros_ingressado',
            new_name='membros_ingressados',
        ),
    ]
